export const GET_WORKBOOKS = "GET_WORKBOOKS";
export const RESET_WORKBOOK_STATUS = "RESET_WORKBOOK_STATUS";
export const SET_NEW_WORKBOOK_START = "SET_NEW_WORKBOOK_START";
export const SET_NEW_WORKBOOK_SUCCESS = "SET_NEW_WORKBOOK_SUCCESS";
export const SET_NEW_WORKBOOK_ERROR = "SET_NEW_WORKBOOK_ERROR";
