export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SET_SIGNED_IN_USER_DATA = "SET_SIGNED_IN_USER_DATA";
export const USER_LOGOUT = "USER_LOGOUT";
