export const GET_WORKSPACES = "GET_WORKSPACES";
export const SET_NEW_WORKSPACE_START = "SET_NEW_WORKSPACE_START";
export const SET_NEW_WORKSPACE_SUCCESS = "SET_NEW_WORKSPACE_SUCCESS";
export const SET_NEW_WORKSPACE_ERROR = "SET_NEW_WORKSPACE_ERROR";
export const RESET_WORKSPACE_STATUS = "RESET_WORKSPACE_STATUS";
