export const GET_WORKPLACES = "GET_WORKPLACES";
export const DELETE_WORKPLACE_SUCCESS = "DELETE_WORKPLACE_SUCCESS";
export const DELETE_WORKPLACE_ERROR = "DELETE_WORKPLACE_ERROR";
export const RESET_DELETE_STATUS = "RESET_DELETE_STATUS";
export const SET_NEW_WORKPLACE_START = "SET_NEW_WORKPLACE_START";
export const SET_NEW_WORKPLACE_SUCCESS = "SET_NEW_WORKPLACE_SUCCESS";
export const SET_NEW_WORKPLACE_ERROR = "SET_NEW_WORKPLACE_ERROR";
export const RESET_WORKPLACE_STATUS = "RESET_WORKPLACE_STATUS";
